name: example
description: "Flowin Design Example Project"
publish_to: 'none'
version: 0.2.1

environment:
  sdk: ^3.9.0

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.7
  flowin_design:
    path: ../
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.0
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  lucide_icons_flutter: ^3.0.7
  package_info_plus: ^8.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
